INSERT INTO SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (1,  'DAVID WARNER' , 30 ,  'Ahmedabad' ,106, 2000.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (2, 'SHIKAR DHAWAN', 25, 'Delhi',104, 1500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (3, 'KANE WILLIAMSON', 23, 'Kota',10, 2000.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (4, 'YUVRAJ SINGH', 25, 'Mumbai',98, 6500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (5, 'MOISES HENRIQUES', 27, 'Bhopal',54, 8500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (6, 'DEEPAK HOODA', 22, 'MP',34, 4500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (7 ,'NAMAN OJHA', 32, 'Ahmedabad',65, 2000.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (8 ,'RASHID KHAN', 25, 'Delhi',6, 1500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (9, 'BHUVNESHWAR KUMAR', 23, 'Kota',100, 2000.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (10, 'MOHAMMED SIRAJ', 25, 'Mumbai',1, 6500.00 );

INSERT INTO  SRH_TEAM (ID,NAME,DOB,POB,NOMATCHES,SALARY)
VALUES (11, 'SIDDARTH KAUL', 27, 'Bhopal',2, 8500.00 );

